### ISSUE TITLE
Change model format

### ISSUE THREAD

**Issue by nhtlongcs** [HCMUS-ROBOTICS/ssdf-lane-seg#4]
https://github.com/HCMUS-ROBOTICS/ssdf-lane-seg/blob/88453953a225748e3e983cc3c80e6bb3e37372cf/src/lane_seg/unet_model.py#L33

The old checkpoint format is decrypted. For upcoming version of **nncore**, please use `data[model_state_dict]` instead
For example:
```
weight = torch.load(model_path, map_location='cpu')[model_state_dict]
```

**Comment by wan2000** [comment]
Does `model_state_dict` should be in the quote like `data['model_state_dict']`, right?
Just to make sure.

**Comment by nhtlongcs** [comment]
Yes, my mistake 😅

**Comment by wan2000** [comment]
Ok if you have a new checkpoint, please let me know.
I will test it with the new format.
